### ISSUE TITLE
Grupos

### ISSUE THREAD

**Issue by jemaf** [COLTEC-DAW/Recuperacao-2o-Trimestre#1]
Responder a issue fornecendo os integrantes do grupo.

Exemplo:

**Grupo X**
Integrantes: Fulano, Beltrano
Repositório: https://www.github.com/.....

**Comment by joaovitorbraga** [comment]
Grupo 1
Integrantes: João Vítor Braga
Repositório: https://github.com/joaovitorbraga/Recuperacao-2o-Trimestre
Obs.: Funcionalidades 1 e 3.

**Comment by IcaroAdao** [comment]
Grupo 2
Integrantes: Ícaro e Mateus Bernardo
 [Repositório](https://github.com/IcaroColtec/Recuperacao-2o-Trimestre)
